/*
 *  Copyright (C) 2024-2026 Claude Dumas <claudedumas63@protonmail.com>. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/#AGPL/>.
 */

#ifndef FESTREAM_H
#define FESTREAM_H

#include "constants.h"
#include "csd.h"
#include <QDate>
#include <QList>
#include <QWeakPointer>

/**
 * @class FeStream
 * @brief Represent a stream of Financial Events (a.k.a. FE) generated by a Csd, for which it
 * keeps a reference to (weak pointer). The stream is accessed through indexed or date-based
 * methods.
 * @details The implementation is optimized for performance and not for low memory usage.
 * This is why it is not using QMap<QDate,Fe> as before, but a QList<qint64> which contains a
 * value for every day in the max period allowed by Scenario (see constants.h). When there is a FE
 * for a given day, the value contains the FE amount, otherwise it contains -1 (meaning entry
 * unused). This makes the array big and of constant size, even for a single FE generated, but
 * this approach has the advantage to be extremely fast for reading and writing.
 *
 * @note To read from the stream, use get() or contains(). To modify the stream, use set() and
 * remove() which validate inputs and maintain internal counters. Use size() and count() to
 * query the stream dimensions.
 */
class FeStream
{
public:

    /**
    * @brief Max number of days that can be found in a FeStream. This is used
    * to limit the size of the internal array.
    */
    static const quint32 MAX_DAYS = 366 * Constants::MAX_DURATION_FE_GENERATION;

    // *** Constructors and destructors ***

    /**
     * @brief Defaut constructor, cannot be used.
     */
    FeStream() = delete;

    /**
     * @brief Constructor. The reference CSD may be dummy at this stage.
     * @param noOfDays No of days of Financial events allowed. Must be > 0 and <= MAX_DAYS.
     * @param csdPtr Reference to the CSD having generated this FE Stream.
     * @param firstDate The date associated with the first element (index 0) in the stream.
     * @throw std::invalid_argument if noOfDays = 0.
     * @throw std::invalid_argument if noOfDays > MAX_DAYS.
     * @throw std::invalid_argument if the Csd pointed to by csdPtr does not exist.
     * @throw std::invalid_argument if firstDate is invalid.
     */
    FeStream(quint32 noOfDays, QWeakPointer<Csd> csdPtr, const QDate& firstDate);

    /**
     * @brief Constructor used for unit testing only.
     */
    FeStream(QDate tomorrow, quint32 maxNoOfDays, QWeakPointer<Csd> csdPtr,
        const QMap<QDate, double> &data);

    // *** Operators ***
    bool operator==(const FeStream &o) const;
    bool operator!=(const FeStream &o) const;
    FeStream& operator=(const FeStream&o) ;

    // *** Methods ***

    /**
     * @brief Mark all elements to NOT in use.
     */
    void reset();

    /**
     * @brief Get the amount for a specific day.
     * @param day The day index (0 = firstDate, 1 = firstDate+1, etc.)
     * @return The amount at the given day, or -1 if no amount is set.
     * @throw std::out_of_range if day >= noOfDays.
     */
    qint64 get(quint32 day) const;

    /**
     * @brief Get the amount for a specific date.
     * @param date The date to query.
     * @return The amount for that date, or -1 if no amount is set.
     * @throw std::invalid_argument if date is invalid.
     * @throw std::invalid_argument if date is before firstDate.
     * @throw std::invalid_argument if date is beyond the range of this stream.
     */
    qint64 get(const QDate& date) const;

    /**
     * @brief Set an amount for a specific day with validation. This is the preferred method
     * for modifying the stream as it validates the amount and maintains the internal element
     * counter.
     * @param day Day of occurrence, with 0 = firstDate and so on. Max value is (noOfDays-1).
     * @param amount The amount, in decimal format. Limited to
     * CurrencyHelper::maxValueAllowedForAmount().
     * @throw std::out_of_range if day >= noOfDays.
     * @throw std::invalid_argument if amount is above the maximum allowed
     * @note Use this method instead of direct assignment to ensure validation and proper
     * tracking of noOfElementsUsed.
     */
    void set(quint32 day, quint64 amount);

    /**
     * @brief Set an amount for a specific date with validation. This is the preferred method
     * for modifying the stream as it validates the amount and maintains the internal element
     * counter.
     * @param date The date for which to set the amount.
     * @param amount The amount, in decimal format. Limited to
     * CurrencyHelper::maxValueAllowedForAmount().
     * @throw std::invalid_argument if date is invalid.
     * @throw std::invalid_argument if date is before firstDate.
     * @throw std::invalid_argument if date is beyond the range of this stream.
     * @throw std::invalid_argument if amount is above the maximum allowed
     * @note Use this method instead of direct assignment to ensure validation and proper
     * tracking of noOfElementsUsed.
     */
    void set(const QDate& date, quint64 amount);

    /**
     * @brief Reset the content for a day to "unused" and maintains the internal element counter.
     * This is the preferred method for removing amounts from the stream.
     * @param day The day to reset, with 0 = firstDate and so on. Max value is (noOfDays-1).
     * @throw std::out_of_range if day >= noOfDays.
     * @note Use this method to properly track noOfElementsUsed.
     */
    void remove(quint32 day);

    /**
     * @brief Reset the content for a date to "unused" and maintains the internal element counter.
     * This is the preferred method for removing amounts from the stream.
     * @param date The date to reset.
     * @throw std::invalid_argument if date is invalid.
     * @throw std::invalid_argument if date is before firstDate.
     * @throw std::invalid_argument if date is beyond the range of this stream.
     * @note Use this method to properly track noOfElementsUsed.
     */
    void remove(const QDate& date);

    /**
     * @brief Check if a specific day has a value set (not -1).
     * @param day The day index (0 = firstDate, 1 = firstDate+1, etc.)
     * @return true if the day has a value, false otherwise.
     * @throw std::out_of_range if day >= noOfDays.
     */
    bool contains(quint32 day) const;

    /**
     * @brief Check if a specific date has a value set (not -1).
     * @param date The date to check.
     * @return true if the date has a value, false otherwise.
     * @throw std::invalid_argument if date is invalid.
     * @throw std::invalid_argument if date is before firstDate.
     * @throw std::invalid_argument if date is beyond the range of this stream.
     */
    bool contains(const QDate& date) const;

    /**
     * @brief Check if the stream has no values set.
     * @return true if noOfElementsUsed == 0, false otherwise.
     */
    bool isEmpty() const;

    /**
     * @brief Get the total number of days this stream can hold.
     * @return The number of days (same as getNoOfDays()).
     */
    quint32 size() const;

    /**
     * @brief Get the number of days that have values set.
     * @return The number of used elements (same as getNoOfElementsUsed()).
     */
    quint32 count() const;

    /**
     * @brief Return a string representation of this object (for debugging purpose). Unused
     * entries are not considered.
     * @return The String representation.
     */
    QString toString();


    // *** Getters / Setters ***
    QWeakPointer<Csd> getCsdPtr() const;
    void setCsdPtr(QWeakPointer<Csd> newCsdPtr);
    quint32 getNoOfElementsUsed() const;
    quint32 getNoOfDays() const;
    QDate getFirstDate() const;
    QDate getLastDate() const;

private:

    /**
     * @brief Convert a date to an index in the amountSet array.
     * @param date The date to convert.
     * @return The index corresponding to the date.
     * @throw std::invalid_argument if date is invalid.
     * @throw std::invalid_argument if date is before firstDate.
     * @throw std::invalid_argument if date is beyond the range of this stream.
     */
    quint32 dateToIndex(const QDate& date) const;

    /**
     * @brief List of all the amounts (>0) generated for every day from firstDate (index 0)
     * till the max allowed for a scenario. If an entry is == -1, it means it is NOT in use.
     * @details Each element holds an amount in decimal format, always >= 0 even for expense
     * Cds. If < 0, it means the element is NOT in use.
     */
    QList<qint64> amountSet;

    /**
     * @brief The date associated with the first element (index 0) in the amountSet.
     */
    QDate firstDate;

    /**
     * @brief No of days this FE stream has. First day is always "firstDate". Minimum value
     * is 1.
     * @details This correspond to the size of the internal amountSet array.
     */
    quint32 noOfDays;

    /**
     * @brief Reference to the Csd having generated this FE stream. This is a weak pointer.
     */
    QWeakPointer<Csd> csdPtr;

    /**
     * @brief No of elements in use in the array.
     */
    uint noOfElementsUsed;
};

#endif // FESTREAM_H
