/*
 *  Copyright (C) 2024-2025 Claude Dumas <claudedumas63@protonmail.com>. All rights reserved.
 *  DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <https://www.gnu.org/licenses/#AGPL/>.
 */

#ifndef FESTREAM_H
#define FESTREAM_H

#include "constants.h"
#include "csd.h"
#include <QList>
#include <QWeakPointer>

/**
 * @class FeStream
 * @brief Represent a stream of Financial Events (a.k.a. FE) generated by a Csd, for which it
 * keeps a reference to (weak pointer).
 * @details The implementation is optimized for performance and not for low memory usage.
 * This is why it is not using QMap<QDate,Fe> as before, but a QList<qint64> which contains a
 * value for every day in the max period allowed by Scenario (see constants.h). When there is a FE
 * for that day, the value contains the FE amount, otherwise it contains -1 (meaning entry unused).
 * This makes the array big and of constant size even for a single FE generated, but this approach
 * has the advantage to be extremely fast for read and write.
 *
 */
class FeStream
{
public:

    /**
    * @brief Max number of days that can be found in a FeStream. This is used
    * to limit the size of the internal array.
    * @details The real number would change according to the starting date. This value slightly
    * above the real max possible, but close enough.
    */
    static const quint32 MAX_DAYS = 366 * Constants::MAX_DURATION_FE_GENERATION;


    // *** Constructors and destructors ***

    /**
     * @brief Defaut constructor, cannot be used.
     */
    FeStream() = delete;

    /**
     * @brief Constructor. The reference CSD may be dummy at this stage.
     * @param noOfDays No of days of Financial events allowed. Must be > 0 and <= MAX_DAYS.
     * @param csdPtr Reference to the CSD having generated this FE Stream.
     * @throw std::invalid_argument if noOfDays = 0.
     * @throw std::invalid_argument if noOfDays > MAX_DAYS.
     * @throw std::invalid_argument if the Csd pointed to by csdPtr does not exist.
     */
    FeStream(quint32 noOfDays, QWeakPointer<Csd> csdPtr);

    /**
     * @brief Constructor used for unit testing only.
     */
    FeStream(QDate tomorrow, quint32 maxNoOfDays, QWeakPointer<Csd> csdPtr,
        QMap<QDate, double> data);

    // *** Operators ***
    bool operator==(const FeStream &o) const;
    bool operator!=(const FeStream &o) const;
    FeStream& operator=(const FeStream&o) ;

    // *** Methods ***

    /**
     * @brief Mark all elements to NOT in use.
     */
    void reset();

    /**
     * @brief Set an amount for a specific day. There could be already a value for this day
     * or it could be unused.
     * @param day Day of occurrence, with tomorrow = 0 and so on. Max value is (noOfDays-1).
     * @param amount The amount, in decimal format. Limited to
     * CurrencyHelper::maxValueAllowedForAmount().
     * @throw std::invalid_argument if day is above (noOfDays-1).
     * @throw std::invalid_argument if amount is above the maximum allowed
     */
    void add(quint32 day, quint64 amount);

    /**
     * @brief Reset the content for a day to "unused". There could be already a value for this day
     * or it could be unused.
     * @param day The day to reset, with 0 being tomorrow, and so on. Max value is (noOfDays-1).
     * @throw std::invalid_argument if day is above (noOfDays-1).
     */
    void remove(quint32 day);

    /**
     * @brief Return a string representation of this object (for debugging purpose). Unused
     * entries are not considered.
     * @return The String representation.
     */
    QString toString();


    // *** Getters / Setters ***

    QList<qint64> getAmountSet() const;
    QWeakPointer<Csd> getCsdPtr() const;
    void setCsdPtr(QWeakPointer<Csd> newCsdPtr);
    quint32 getNoOfElementsUsed() const;
    quint32 getNoOfDays() const;

private:

    /**
     * @brief List of all the amounts (>0) generated for every day from tomorrow (index 0)
     * till the max allowed for a scenario. If an entry is == -1, it means it is NOT in use.
     * @details Each element holds an amount in decimal format, always >= 0 even for expense Cds.
     * If < 0, it means the element is NOT in use.
     */
    QList<qint64> amountSet;

    /**
     * @brief No of days this FE stream has. First day is always "tomorrow".
     * @details This correspond to the size of the internal amountSet array.
     */
    quint32 noOfDays;

    /**
     * @brief Reference to the Csd having generated this FE stream. This is a weak pointer.
     */
    QWeakPointer<Csd> csdPtr;

    /**
     * @brief No of elements in use in the array.
     */
    uint noOfElementsUsed;
};

#endif // FESTREAM_H
